package com.ph.teabar.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import teabar.ph.com.teabar.pojo.Equpment;
import teabar.ph.com.teabar.pojo.Friend;
import teabar.ph.com.teabar.pojo.FriendInfor;
import teabar.ph.com.teabar.pojo.UserEntry;

import com.ph.teabar.database.dao.EqupmentDao;
import com.ph.teabar.database.dao.FriendDao;
import com.ph.teabar.database.dao.FriendInforDao;
import com.ph.teabar.database.dao.UserEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equpmentDaoConfig;
    private final DaoConfig friendDaoConfig;
    private final DaoConfig friendInforDaoConfig;
    private final DaoConfig userEntryDaoConfig;

    private final EqupmentDao equpmentDao;
    private final FriendDao friendDao;
    private final FriendInforDao friendInforDao;
    private final UserEntryDao userEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equpmentDaoConfig = daoConfigMap.get(EqupmentDao.class).clone();
        equpmentDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        friendInforDaoConfig = daoConfigMap.get(FriendInforDao.class).clone();
        friendInforDaoConfig.initIdentityScope(type);

        userEntryDaoConfig = daoConfigMap.get(UserEntryDao.class).clone();
        userEntryDaoConfig.initIdentityScope(type);

        equpmentDao = new EqupmentDao(equpmentDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);
        friendInforDao = new FriendInforDao(friendInforDaoConfig, this);
        userEntryDao = new UserEntryDao(userEntryDaoConfig, this);

        registerDao(Equpment.class, equpmentDao);
        registerDao(Friend.class, friendDao);
        registerDao(FriendInfor.class, friendInforDao);
        registerDao(UserEntry.class, userEntryDao);
    }
    
    public void clear() {
        equpmentDaoConfig.clearIdentityScope();
        friendDaoConfig.clearIdentityScope();
        friendInforDaoConfig.clearIdentityScope();
        userEntryDaoConfig.clearIdentityScope();
    }

    public EqupmentDao getEqupmentDao() {
        return equpmentDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public FriendInforDao getFriendInforDao() {
        return friendInforDao;
    }

    public UserEntryDao getUserEntryDao() {
        return userEntryDao;
    }

}
