package com.ph.teabar.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import teabar.ph.com.teabar.pojo.Equpment;

import com.ph.teabar.database.dao.EqupmentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equpmentDaoConfig;

    private final EqupmentDao equpmentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equpmentDaoConfig = daoConfigMap.get(EqupmentDao.class).clone();
        equpmentDaoConfig.initIdentityScope(type);

        equpmentDao = new EqupmentDao(equpmentDaoConfig, this);

        registerDao(Equpment.class, equpmentDao);
    }
    
    public void clear() {
        equpmentDaoConfig.clearIdentityScope();
    }

    public EqupmentDao getEqupmentDao() {
        return equpmentDao;
    }

}
